### ISSUE TITLE
still: error when requiring leap_year.rb from the command line without absolute path

### ISSUE THREAD

**Issue by bl00dymarie** [rubymonsters/testing-for-beginners#6]
In the section "Separating test code", running `ruby -I -r leap_year.rb -e "p leap_year?(1996)"` from the command line gives a LoadError. My workaround was to load:

1. `./leap_year.rb` OR
2. `~/path-to-my-folder/leap_year.rb`

If I include `-I` the output will always be (we want `true` instead):
```
2001: false
1900: false
2000: true
2004: true
```
So I exluded `-I` and got the expected output.

@alicetragedy opened this [issue](https://github.com/rubymonsters/testing-for-beginners/issues/3) and it apparently couldn't fix this new error.

**Comment by plexus** [comment]
Sorry to budge in here. The `-I` flag to ruby adds a directory to the "load path", this is the list of all the places where ruby looks for files to require. To load files from the current directory you can use `-I .`

This should do the trick:

`ruby -I . -r leap_year -e "p leap_year?(1996)"`

**Comment by plexus** [comment]
Hi @lilaluca, I made a small change to the text. I hope it works for you now!

Have fun testing :)

**Comment by bl00dymarie** [comment]
Ok thanks @plexus it does work thanks to the `.` \o/
